CREATE DATABASE IF NOT EXISTS serkom;
USE serkom;

CREATE TABLE IF NOT EXISTS bangun_datar (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(100) NOT NULL,
    luas DOUBLE NOT NULL,
    keliling DOUBLE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
